# Generated by Django 2.2.9 on 2020-06-05 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Model', max_length=100)),
                ('status', models.CharField(default='Data Required', max_length=50)),
                ('codepath', models.CharField(default='', max_length=200)),
                ('date_create', models.DateTimeField(verbose_name='date created')),
                ('type', models.IntegerField(default=0)),
                ('finished_steps', models.CharField(default='', max_length=10)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('Faculties', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('Students', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('Talks', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('Events', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('Periods', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('FacultyTime', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('TalkTime', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('TalkPref', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('StudentsPref', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('EventsTime', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('ActivityCapacity', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('Rooms', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('FacultyNeedRoom', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('RoomCapacity', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('RoomTime', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('ResultsFaculty', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('ResultsStudent', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('ResultsRoom', django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatype', models.CharField(choices=[('Faculty Time', 'Faculty Time'), ('Activity Capacity', 'Activity Capacity'), ('Faculty Room', 'Faculty Room'), ('Student Preference', 'Student Preference'), ('Talk Time', 'Talk Time'), ('Talk Preference', 'Talk Preference'), ('Event Time', 'Events Time'), ('Event Preference', 'Events Preference'), ('Room Time', 'Room Time'), ('Room Capacity', 'Room Capacity')], max_length=100)),
                ('docfile', models.FileField(upload_to=main.models.filepath)),
                ('date_upload', models.DateTimeField(verbose_name='date uploaded')),
                ('notes', models.CharField(default='No Notes', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
