# Generated by Django 2.2.9 on 2021-02-12 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optmodel',
            name='Duration',
            field=django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None),
        ),
        migrations.AddField(
            model_name='optmodel',
            name='LowerLimit',
            field=django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None),
        ),
        migrations.AddField(
            model_name='optmodel',
            name='ResultsFacultyFileLoc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='optmodel',
            name='ResultsStudentFileLoc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='optmodel',
            name='UpperLimit',
            field=django_mysql.models.ListTextField(models.CharField(max_length=10), default=[], size=None),
        ),
        migrations.AddField(
            model_name='optmodel',
            name='n_val',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='optmodel',
            name='p_val',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='optmodel',
            name='t_val',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='DataDocumentNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=main.models.filepath)),
                ('date_upload', models.DateTimeField(verbose_name='date uploaded')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
